### ISSUE TITLE
Links with spaces in the target don't work

### ISSUE THREAD

**Issue by davidblackzipier** [erusev/parsedown-extra#103]
Put this into http://parsedown.org/extra/
```
[google](https://www.google.com)

[google]( https://www.google.com )
```
The first link works fine, but the second link just shows up as plain text. The second link works fine in PHP Markdown Extra but not in Parsedown Extra.

**Comment by erusev** [comment]
@aidantwoods

Want to create a PR for this?

**Comment by aidantwoods** [comment]
@erusev can take a look :)
