### ISSUE TITLE
I Created a Laravel Wrapper...

### ISSUE THREAD

**Issue by bhuvidya** [erusev/parsedown-extra#116]
Hi there. Just to let you know I created a Laravel wrapper for parsedown-extra based on the parsedown/laravel wrapper for the standard parsedown package. My repo can be found at https://github.com/bhuvidya/laravel-parsedown-extra

Thanks for the great markdown parsers!

Cheers.

**Comment by erusev** [comment]
Feel free to include it in https://github.com/erusev/parsedown/wiki/Extensions-and-Related-Libraries.

**Comment by bhuvidya** [comment]
Cheers! Done.
