### ISSUE TITLE
The current release is broken with the latest parsedown version

### ISSUE THREAD

**Issue by LukasKnuth** [erusev/parsedown-extra#121]
[25 Days ago](https://github.com/erusev/parsedown/commit/098f24d189d17f6cadfdb135de6aa241576f3e35#diff-ed0d3da57330712681e64f838087ea47L516), the internal structure of some elements was changed. This broke this library in multiple places.

The fix for it was added [9 Days ago](https://github.com/erusev/parsedown-extra/commit/bbf74b5f2a89b8c193f87fdc432806bc63cb0467#diff-6e93544faea52addc25721be4082dbb8L206), but this is not yet available over composer.

That means, the latest versions of parsedown and parsedown-extra are not compatible. I realize that the current 1.8 release of parsedown is a beta release, but it doesn't say that it's incompatible anywhere.

**Comment by aidantwoods** [comment]
> That means, the latest versions of parsedown and parsedown-extra are not compatible. 

The latest release of Parsedown is 1.7.1, a stable version of 1.8 hasn't yet been released:

![screen shot 2018-04-15 at 23 21 43](https://user-images.githubusercontent.com/3288888/38784055-d71466a2-4103-11e8-978f-86fd1c3ecd1b.png)

>  I realize that the current 1.8 release of parsedown is a beta release, but it doesn't say that it's incompatible anywhere.

I hate to be that guy, but... like... it's marked as a pre-release. I'm not sure what you expect? A pre-release almost certainly going to have issues in it – the whole point in labelling it like this is to distinguish it from a stable release.

![screen shot 2018-04-15 at 23 51 51](https://user-images.githubusercontent.com/3288888/38784319-033998d4-4108-11e8-86c3-22743b7fb260.png)


As far as I know, composer and packagist should take note of the pre-release flag and won't auto-update anything.

For example:
<img width="837" alt="screen shot 2018-04-15 at 23 27 33" src="https://user-images.githubusercontent.com/3288888/38784090-a0723e7a-4104-11e8-9748-5af9599d0fe0.png">

I even tried locally cloning the repo you referenced this issue from, and Parsedown 1.7.1 (latest stable) is still being downloaded.

<img width="837" alt="screen shot 2018-04-15 at 23 40 48" src="https://user-images.githubusercontent.com/3288888/38784202-7573cde0-4106-11e8-996f-3933c6920e1a.png">

> The fix for it was added 9 Days ago, but this is not yet available over composer.

This is true, I'll probably release a similar beta for Parsedown-extra once the second beta for Parsedown goes out. This will be for the sole purpose of encouraging testing though, so people can file any bugs they find. Please don't rely on beta releases for stuff that you would like to work.

Generally the best way to avoid these kinds of stability issues is to avoid pre-release software. I'm a little stumped as to how you could have managed to install this accidentally, unless you're explicitly asking composer to install an unstable version?

**Comment by LukasKnuth** [comment]
> but... like... it's marked as a pre-release.

Yes, you're right. However, composer _did_ auto-update to the beta-release (for me and everyone in the linked issue).

The issue was actually that the composer-template for Craft CMS (which is the root-project) had `"minimum-stability": "beta"` in it's `composer.json` file, which caused it to update to the beta-release.

Sorry for causing any headache, I just found this today. Thanks for responding anyways! I'm closing this, as the problem is resolved.
