### ISSUE TITLE
 Call to undefined method ParsedownExtra::textElements() in /var/www/html/app/ParsedownExtra.php on line 46

### ISSUE THREAD

**Issue by dealante** [erusev/parsedown-extra#122]
This happens with the latest `ParseDown.php` version. Note: I did not use composer to install these libraries.

![image](https://user-images.githubusercontent.com/26195637/38784970-48cc610c-40df-11e8-8adf-594041a67250.png)

Here are the includes.

```
<?php
require __DIR__ . '/Mustache/Autoloader.php';
require_once __DIR__ . '/Parsedown.php';
require_once __DIR__ . '/ParsedownExtra.php';

... rest of code ....
```

**Comment by aidantwoods** [comment]
`textElements` is a function that doesn't exist in the latest Parsedown version (nor are calls to it made from the latest Parsedown-extra version).

I think you may have grabbed `ParsedownExtra.php` out of the `master` branch?

If this is the case, you can find the latest **stable** releases of Parsedown and Parsedown-extra here :)
Parsedown: https://github.com/erusev/parsedown/releases/latest
Parsedown Extra: https://github.com/erusev/parsedown-extra/releases/latest

There will be a zip file under each release which will contain the contents of the repo at the time the release happened.
