### ISSUE TITLE
HTML email-specific comments being removed

### ISSUE THREAD

**Issue by hellocosmin** [erusev/parsedown-extra#126]
See the screenshots, Parsedown handles it fine while Extra removes the code:

*Parsedown Extra*
![image](https://user-images.githubusercontent.com/1656595/41058883-a6148ca0-69d3-11e8-9ba9-19888babbaf0.png)

*Parsedown*
![image](https://user-images.githubusercontent.com/1656595/41058889-ac26b1c2-69d3-11e8-9513-cc4905ad8232.png)

**Comment by aidantwoods** [comment]
I believe this is resolved in `0.8.0-beta-1`?

**Comment by hellocosmin** [comment]
Thanks Aidan, guess I'll need to wait for a production release :)
