### ISSUE TITLE
PHP7.4RC2 incompatibility

### ISSUE THREAD

**Issue by storeman** [erusev/parsedown-extra#134]
There were a couple of errors with PHP 7.4RC2.

**`Trying to access array offset on value of type null`**

**Comment by allejo** [comment]
Looks like [this behavior was deprecated in 7.4](https://wiki.php.net/rfc/notice-for-non-valid-array-container).

**Comment by giuscris** [comment]
> Looks like [this behavior was deprecated in 7.4](https://wiki.php.net/rfc/notice-for-non-valid-array-container).

It wasn't. Now that PHP 7.4 has been released I started to get the notice.

**Comment by hamidafghan** [comment]
Waiting for this PR to be merged. 
Any other way to handle it, please?

**Comment by allejo** [comment]
> Waiting for this PR to be merged.
> Any other way to handle it, please?

You can use the [`@` operator](https://www.php.net/manual/en/language.operators.errorcontrol.php) in the meanwhile.

**Comment by ambroisemaupate** [comment]
> Waiting for this PR to be merged.
> Any other way to handle it, please?

I switched to https://github.com/thephpleague/commonmark which is very active

**Comment by allejo** [comment]
@erusev if you're in need of maintainers, I'd gladly volunteer to help triage/maintain things in this repo.
