### ISSUE TITLE
Add Markdown Inside HTML Blocks like Markdown Extra

### ISSUE THREAD

**Issue by bzerangue** [erusev/parsedown-extra#14]
Would be really helpful for Parsedown Extra to add Markdown Inside HTML Blocks

Previously in Markdown, you couldn’t wrap Markdown-formatted content inside a `<div>` element. This is because `<div>` is a block element and plain Markdown does not format the content of such.

Markdown Extra gives you a way to put Markdown-formatted text inside any block-level tag. You do this by adding a markdown attribute to the tag with the value 1 — which gives markdown="1" — like this:

```
<div markdown="1">
This is *true* markdown text.
</div>
```

The markdown="1" attribute will be stripped and `<div>`’s content will be converted from Markdown to HTML. The end result will look like this:

```
<div>
<p>This is <em>true</em> markdown text.</p>
</div>
```

https://michelf.ca/projects/php-markdown/extra/#markdown-attr

**Comment by frumbert** [comment]
I think this needs to have a note on it that the markdown tag needs to be on every tag that is a direct parent of the element - so

    <div markdown="1">
        <blockquote>
            this is *true* markdown
       </blockquote>
    </div>

doesn't work but

    <div>
        <blockquote markdown="1">
            this is *true* markdown
       </blockquote>
    </div>

does
