### ISSUE TITLE
Doesn't work on PHP 5.3.3 ?

### ISSUE THREAD

**Issue by DGCK81LNN** [erusev/parsedown-extra#148]
Parsedown.php alone worked fine

Message:
Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /var/www/html/3luo.jedoo.com/ParsedownExtra.php on line 652
Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /var/www/html/3luo.jedoo.com/ParsedownExtra.php on line 652
Warning: DOMDocument::loadHTML(): Empty string supplied as input in /var/www/html/3luo.jedoo.com/ParsedownExtra.php on line 631
Catchable fatal error: Argument 1 passed to DOMNode::removeChild() must be an instance of DOMNode, null given, called in /var/www/html/3luo.jedoo.com/ParsedownExtra.php on line 656 and defined in /var/www/html/3luo.jedoo.com/ParsedownExtra.php on line 632

**Comment by DGCK81LNN** [comment]
The argument 1 of DOMDocument::saveHTML() was added in PHP 5.3.6, which seemed to have caused the problem.

**Comment by xf-** [comment]
Support for PHP 5.3 ended over 5 years ago.
https://en.wikipedia.org/wiki/PHP#Release_history

**Comment by DGCK81LNN** [comment]
Sorry for bothering.

**Comment by DGCK81LNN** [comment]
Sorry for bothering, but I don't own the server. Nothing I can do about the old PHP version ~_~
