### ISSUE TITLE
Line breaks, multiple paragraphs inside footnotes

### ISSUE THREAD

**Issue by philgruneich** [erusev/parsedown-extra#22]
This snippet from the documentation:

    [^1]:
        And that's the footnote.
    
        That's the second paragraph.

Doesn't render a footnote.

    <p>[^1]:</p>
    <pre><code>And that's the footnote.
    
    That's the second paragraph.</code></pre>

**Comment by erusev** [comment]
The latest release resolves this.

**Comment by CalebGrove** [comment]
Thank you, wonderful work!
