### ISSUE TITLE
Over-aggressive abbreviations

### ISSUE THREAD

**Issue by nwtn** [erusev/parsedown-extra#26]
Input:

````
AMW

*[AMW]: auxiliary midwife
*[MW]: midwife
````

Expected output (which *is* produced by PHP Markdown Extra):

````
<p><abbr title="auxiliary midwife">AMW</abbr></p>
````

Actual, incorrect output from Parsedown Extra:

````
<p><abbr title="auxiliary midwife">A<abbr title="midwife">MW</abbr></abbr></p>
````

**Comment by erusev** [comment]
The latest release resolves this. You can test it in [the demo](http://parsedown.org/extra/).

**Comment by nwtn** [comment]
Amazing, thanks!
