### ISSUE TITLE
The Mark tag

### ISSUE THREAD

**Issue by james2doyle** [erusev/parsedown-extra#3]
I was reading an article on a site that used the `mark` tag a lot. Then I happened to see some markdown parser that supported it via `==marked up text==`.

``` markdown
This is an ==interactive== demo of Parsedown.
```

This would parse out to this:

``` html
<p>This is an <mark>interactive</mark> demo of Parsedown.</p>
```

From the HTMLDoctor site:

> Previously, you may have used em and strong for adding emphasis or importance, respectively, to portions of text. mark differs from these two as it is used purely for highlighting the relevance of a piece of text to the user and/or page’s content. In the past you may have used em and strong for this purpose, which was arguably valid at the time due to the lack of a better element, but the introduction of mark simply means their use will be more strict.
> 
> Use strong when you need to indicate the importance of a piece of text, such as an error or warning message, and em should be for adding emphasis to text, stressing words to adapt the meaning of a sentence.

I know that Markdown extra doesnt support this. But I can see it being quite useful for some sites that are writing proper articles as opposed to posts about their cat and the sandwhich they had that morning.

Any thoughts?

**Comment by davejamesmiller** [comment]
I was also looking for this, because I'm converting some code from [Redcarpet](https://github.com/vmg/redcarpet). I added it in a custom subclass instead. Here's the code, in case it helps anyone else:

```php
class Markdown extends ParsedownExtra
{
    public function __construct()
    {
        parent::__construct();

        $this->inlineMarkerList .= '=';
        $this->InlineTypes['='] = ['Mark'];
    }

    protected function inlineMark($Excerpt)
    {
        if (preg_match('/^==(.+?)==/s', $Excerpt['text'], $matches)) {
            return [
                'extent'  => strlen($matches[0]),
                'element' => [
                    'name'    => 'mark',
                    'handler' => 'line',
                    'text'    => $matches[1],
                ],
            ];
        }
    }
}
```
