### ISSUE TITLE
Recent changes to parsedown have broken parsedown-extra

### ISSUE THREAD

**Issue by manthano** [erusev/parsedown-extra#31]
You're probably aware of this, but I was trying to use parsedown/parsedown extra in a project today and the recent changes to the method names in parsedown (e.g. identify<type> to block<type>, Span to Inline) haven't been reflected in parsedown-extra so it doesn't work with the current version of parsedown.

**Comment by erusev** [comment]
You should use [a release version](https://github.com/erusev/parsedown/releases) of Parsedown. 

The code in the master branch is work in progress.

I'll think about using a separate branch for development to avoid this kind of confusion in future.
