### ISSUE TITLE
classes on images no longer working with 0.3.0+

### ISSUE THREAD

**Issue by rhukster** [erusev/parsedown-extra#32]
I can't get the markdown extra syntax for extra classes to work any longer:

```
![](https://octodex.github.com/images/gracehoppertocat.jpg) {.github}
```

Results in:

```
<img src="https://octodex.github.com/images/gracehoppertocat.jpg" alt="">
```

Class is missing.  This was working prior to the refactor of parsedown from 1.1.4 to 1.2.0 and the associated changes in parsedown-extra. I just is no longer available in the $excerpt.

**Comment by rhukster** [comment]
Actually this might be my own fault.  I'm using a Trait to override some behavior, and I think it might not be taking into account all the changes you made in 1.2.0.  Debugging deeper now...

**Comment by rhukster** [comment]
Nope, it's not me, it's caused by the separation of links and images into two methods.  Basically the class is found but its lost in the chain of parent calls.

**Comment by rhukster** [comment]
Ok, i attempted to fix this but reached an impasse. 

First I  had to create an `inlineImage()` method in ParsedownExtra as it was missing.  However that is not the real issue...

The problem really occurs when things trickle back to `Parsedown::inlineImage()` and the `$Inline` element comes back from `inlineLink()` with the class attribute intact.  However, this being the non-extra class, manually rebuilds the `$Inline` element ignoring the class attribute. It is at this point the class is lost.

So when `$Inline` is eventually returned to `ParsedownExtra::inlineImage()`, the class is gone, so there's no extra elements found to add.

Maybe it's a Saturday, maybe i've spent too long in front of the computer today, but i'm stuck here, and can see no simple way to resolve short of putting logic into the `Parsedown::inlineImage()` method to add attributes if they exist.  Any resolution to this would be welcome.

**Comment by rhukster** [comment]
Ok, so i have a fix that doesn't rebuild the Inline Image element, it merely manipulates it.  This way anything extra is not lost. I don't find it particulary 'pretty', but it does work and maintains the class attributes for ParsedownExtra:

It is a change for the `Parsedown::inlineImage()` method.

## Parsedown.php
```
    protected function inlineImage($excerpt)
    {
        if ( ! isset($excerpt[1]) or $excerpt[1] !== '[')
        {
            return;
        }

        $excerpt = substr($excerpt, 1);

        $Inline = $this->inlineLink($excerpt);

        $backup = $Inline;

        if ($Inline === null)
        {
            return;
        }

        $Inline['extent'] ++;

        $Inline['element']['name'] = 'img';
        $Inline['element']['attributes']['src'] = $Inline['element']['attributes']['href'];
        unset($Inline['element']['attributes']['href']);

        $Inline['element']['attributes']['alt'] = $Inline['element']['text'];
        unset($Inline['element']['text']);

        return $Inline;
    }
```

I hesitate to submit a pull request because I'm sure there's a nicer way to handle this.

**Comment by rhukster** [comment]
For completeness here are my changes:

**Parsedown.php** - https://github.com/rhukster/parsedown/commit/03ff22c7df8e4aac3a5a309df5f6edb0685b6e0b

**ParsedownExtra.php** - https://github.com/rhukster/parsedown-extra/commit/41dd6f766bf6745c4c6201ed4d95f934ac3c0f94

**Comment by erusev** [comment]
That's an impressive piece of work.

I believe that the changes in Parsedown.php are sufficient .

I'm merging the pull request.

**Comment by erusev** [comment]
p.s. I'm adding [Grav](http://getgrav.org/) to Parsedown's README.

**Comment by rhukster** [comment]
Great Thanks!
