### ISSUE TITLE
Warning: array_unshift() expects parameter 1 to be array, null given in ParsedownExtra.php on line 31

### ISSUE THREAD

**Issue by hollodotme** [erusev/parsedown-extra#34]
Hi, since parsedown version 1.2.0 there is this E_WARNING coming up when using parsedown-extra.

Trace:
```
...
ParsedownExtra->__construct( )
array_unshift () in ParsedownExtra.php:31
```

**Comment by erusev** [comment]
Hi,

Do you update both ParsedownExtra.php and Parsedown.php?

Is there a specific markdown text that triggers this warning?

**Comment by hollodotme** [comment]
Ah, damn! composer.lock prevented the update of parsedown-extra.
Sorry for that, all fine!

**Comment by erusev** [comment]
No problem.

> composer.lock prevented the update of parsedown-extra

Could you tell me more about that?

**Comment by hollodotme** [comment]
I'am using https://github.com/hollodotme/treemdown as a dependency of a current application.
hollodotme/treemdown has the dependency to parsedown-extra (version ~>0.1.0) and my other application has a dependency to parsedown (~>1.0)

So my `composer update` updated parsedown, but not parsedown-extra.

And sorry again, it's not the composer.lock, it is the version restriction in treemdown/composer.json that prevented the update of parsedown-extra.

**Comment by erusev** [comment]
Ah, ok. Thanks.
