### ISSUE TITLE
Parse error in PHP 5.2

### ISSUE THREAD

**Issue by onet4** [erusev/parsedown-extra#35]
Hi nice work.

It seems parsedown-extra does not work in PHP v5.2.

The problematic part seems to be this one.

https://github.com/erusev/parsedown-extra/blob/0.5.1/ParsedownExtra.php#L350-L352

```php
        uasort($this->DefinitionData['Footnote'], function($A, $B) {
            return $A['number'] - $B['number'];
        });
```

**Comment by erusev** [comment]
@onet4 

Is this the only part that is not supported in 5.2.

p.s. 5.2 has security issues. It's recommended that you upgrade.

**Comment by onet4** [comment]
@erusev I'm planning to include your work in my program that is going to be published as a module of a CMS. And the CMS unfortunately still supports PHP 5.2. And it's unknown which PHP version the possible users of the module would use. 

It seems Parsedown works very well with PHP 5.2 so I hope Parsedown Extra as well.

**Comment by erusev** [comment]
I'll think about it. It'd be helpful if you could experiment with it and see if the `uasort` is the only thing that is not supported in 5.2.

**Comment by GrahamCampbell** [comment]
I don't think we should support php 5.2 in parsedown extra.

**Comment by hkdobrev** [comment]
FWIW, the thing not supported here is the inline closure. I'd go with using a static function so it would work on PHP 5.2, but not supporting it. So PHP 5.2-only bugs won't be fixed and if it's tested on PHP 5.2 it could be added to "allow_failures" on Travis CI.

**Comment by GrahamCampbell** [comment]
I think we should just totally not allow php 5.2. People should not be running php 5.2. It's got some serious security issues.

**Comment by reznoa** [comment]
just patch

```
	private static function FootnoteCompFunc($A, $B)
	{
		return $A['number'] - $B['number'];
	}
```

```
        uasort($this->DefinitionData['Footnote'], array('ParsedownExtra', 'FootnoteCompFunc'));
```
