### ISSUE TITLE
Support for [TOC]?

### ISSUE THREAD

**Issue by sikhlana** [erusev/parsedown-extra#36]
I am using DOMDocument to fetch the h1 and h2 tag tree (not a good method I think) to make a tree for my app. Would be awesome if it gets implemented :smile:

**Comment by erusev** [comment]
I'm not sure I understand.

**Comment by sikhlana** [comment]
Well the gist is that when a users adds the [TOC] tag in the markdown it will return an ordered list of all the headings and stuff... [This is the markdown one.](https://github.com/mattfarina/markdown-extra/blob/master/src/mattfarina/MarkdownExtra/Toc.php)

**Comment by erusev** [comment]
Since this is not part of the Markdown Extra specification, I wouldn't add it to Parsedown Extra, but it sounds like a valuable feature. It be nice to have a Parsedown Extra extension that supports it.

**Comment by ghprod** [comment]
:+1:
