### ISSUE TITLE
Rendering breaks at the end of a paragraph with opening tag, but no closing tag

### ISSUE THREAD

**Issue by fitzage** [erusev/parsedown-extra#38]
I have a blog article that I was given in HTML format and didn't feel like converting everything.

All paragraphs have an opening tag, but not a closing tag. While this bugs the heck out of me, it's valid in html5, and I didn't have the urge to change it.

In a previous version of parsedown, it rendered fine. (see here https://www.joyent.com/blog/predicteria-2015)

With the version of parsedown included in Kirby 2.0.6, this page breaks. (see this screenshot of the same article on localhost http://d.pr/i/1dkSl)

If I remove all the opening paragraph tags and replace them with line breaks, the unclosed list item tags later in the article still render fine as list items, so it appears that it's just unclosed paragraphs that's broken.

**Comment by erusev** [comment]
Could you quote a simple Markdown text that I could reproduce the issue with?

**Comment by fitzage** [comment]
Well, it's not really the markdown that's giving me the trouble. Sometimes I'm given content in HTML and don't want to convert it. But here are the first couple of paragraphs.

```
<p>Fifteen years ago, I initiated a time-honored tradition among my colleagues in kernel development at Sun: shortly after the first of every year, we would get together at <a href="http://www.theosteriaavanti.com/">our favorite local restaurant</a> to form predictions for the coming year.  We made one-year, three-year and six-year predictions for both our technologies and more broadly for the industry.  We did this for nine years running &#8212; from 2000 to 2008 inclusive &#8212; and came to know the annual ritual as a play on the restaurant name:  Predicteria.
<p>I have always been interested in our past notions of the future (<a href="http://www.newsweek.com/everything-back-future-ii-got-hilariously-wrong-about-2015-according-293272">hoverboards and self-lacing shoes</a> FTW!), and looking back now at nearly a decade of our predictions has led me to an inescapable (and perhaps obvious) conclusion: <b>predictions tell you more about the present than the future</b>.  That is, predictions reflect the zeitgeist of the day &#8212; both in substance and in tone: in good years, people predict halcyon days; in bad ones, the apocalypse.  And when a particular company or technology happened to be in the news or otherwise on the collective mind, predictions tended to be centered around it: it was often the case that several people would predict that a certain company would be acquired or that a certain technology would flourish &#8212; or perish.  (Let the record reflect that <a href="http://www.itworld.com/article/2702259/data-center/hp-to-replace-itanium-with-x86-in-its-nonstop-server.html">the demise of Itanium</a> was accurately predicted many times over.)
```

I put them in the demo parser, and it also dropped everything after the first paragraph.

**Comment by erusev** [comment]
Top level elements need to be closed. 

A workaround would be to wrap another block-level element around them:

```
<div>
<p>paragraph
<p>paragraph
</div>
```
