### ISSUE TITLE
Adding support for markdown within HTML tags

### ISSUE THREAD

**Issue by fredleblanc** [erusev/parsedown-extra#4]
We've recently included Parsedown (Extra) into Statamic (and, by the way, I love it, it's so quick and does a much, much better job of handling the weird edge cases).

Anyway, someone has submitted a ticket to *our* support system asking about support in Parsedown (Extra) for `markdown="1"` for parsing within HTML elements. (It's part of [Markdown Extra](http://michelf.ca/projects/php-markdown/extra/#markdown-attr)).

So, I'm here doing my due diligence. Is this feature something on the Parsedown Extra roadmap for implementation? Is it perhaps already implemented but slightly different syntax from Markdown Extra?

Thanks for your time (and for such an awesome markdown parser).
Fred

**Comment by erusev** [comment]
The [latest release](https://github.com/erusev/parsedown-extra/releases/tag/0.3.0) resolves this.

p.s. The improvements in Parsedown.php made it possible to implement the whole feature in 5 lines of code.

**Comment by Lakhman** [comment]
Awesome!! Thanks so much!! I'm gonna update now! :+1:

**Comment by erusev** [comment]
Ok, it does work for tags that are nested in tags that have markdown=1, but it still doesn't work for nested tags that are inside of tags that don't have it.

I'm reopening this.

**Comment by erusev** [comment]
Ok, now it should always work.

**Comment by samuelgfeller** [comment]
> Ok, now it should always work.

It does not for me now when I don't specifically add `markdown="1"` to every HTML block.. what am I doing wrong?

This is my code:
```php
$markdown = 'Link: [parsedown](https://parsedown.org/)

<div markdown="1">
Link: [parsedown](https://parsedown.org/)  
</div>

<div>
Link: [parsedown](https://parsedown.org/)  
</div>

<details>
<summary><b>Click to see</b></summary>

## Title  
Link: [parsedown](https://parsedown.org/)   
Code: `codeblock`  
</details>
';

$parser = new ParsedownExtra();
echo $parser->text($markdown);
```

This is the HTML I get:
```html
<p>Link: <a href="https://parsedown.org/">parsedown</a></p>
<div>
<p>Link: <a href="https://parsedown.org/">parsedown</a>  </p>
</div>
<div>
Link: [parsedown](https://parsedown.org/)  
</div>
<details>
<summary><b>Click to see</b></summary>

## Title  
Link: [parsedown](https://parsedown.org/)   
Code: `codeblock`  
</details>
```
