### ISSUE TITLE
processTag failed for javascript

### ISSUE THREAD

**Issue by reznoa** [erusev/parsedown-extra#41]
input:
```
<script>
alert(1);
</script>
```

expected result:
```
<script>
alert(1);
</script>
```

actual result(error):
```
DOMDocument::saveHTML() expects exactly 0 parameters, 1 given(2)
File: /ParsedownExtra.php:492
DOMDocument::saveHTML() expects exactly 0 parameters, 1 given(2)
File: /ParsedownExtra.php:508
```

**Comment by erusev** [comment]
What version to u use? I'm unable to reproduce it with the latest one: http://parsedown.org/extra/.

**Comment by reznoa** [comment]
im using lastest one.

this is my test code:
```
<?php
require_once 'Parsedown.php';
require_once 'ParsedownExtra.php';

$PdExtra = new ParsedownExtra();
echo $PdExtra->text("<script>\nalert(1);\n</script>");
?>
```

**Comment by erusev** [comment]
Which version of PHP is that?

**Comment by reznoa** [comment]
5.2.0.

unfortunately, i can't upgrade it.

**Comment by erusev** [comment]
Some of the classes that `processTag` uses are not supported in 5.2. You could avoid the issue by removing the `blockMarkupComplete` method, but this would also remove the "Markdown inside HTML" feature.

**Comment by microcipcip** [comment]
Change all `saveHTML` to `saveXml` in the ParsedownExtra.php file
