### ISSUE TITLE
Prevent some tag html

### ISSUE THREAD

**Issue by lshaf** [erusev/parsedown-extra#51]
on parse down, is there any easy way to prevent some tag being parsed like `<script>` or `<form>`?

**Comment by erusev** [comment]
I don't think so. You can prevent all tags, though.

**Comment by erusev** [comment]
Perhaps, you might be interested in using http://htmlpurifier.org/.

**Comment by lshaf** [comment]
well I already read it and that way just too complicated, I though you have more simple syntax or idea on it.

thanks for suggest :)
