### ISSUE TITLE
Placeholder attribute is being removed

### ISSUE THREAD

**Issue by bastianallgeier** [erusev/parsedown-extra#53]
When you have some inline html in your Markdown like: 

```
<div><input placeholder="test"></div>
```

…the word "placeholder" gets removed and leaves a broken attribute.

**Comment by stevetrader** [comment]
Has anyone found a workaround for this that doesn't involve js?

**Comment by maxfenton** [comment]
It looks like this is a bug with parsedown using the string `placeholder` as a literal placeholder, and `str_replace`-ing that. Would changing `placeholder` in the parsedown PHP to something like `PD_PLACEHOLDER` fix the issue? (I'd like a sanity-check before making a pull request.)

```
        # because we don't want for markup to get encoded
        $DOMDocument->documentElement->nodeValue = 'placeholder';
        $markup = $DOMDocument->saveHTML($DOMDocument->documentElement);
        $markup = str_replace('placeholder', $elementText, $markup);
```

**Comment by erusev** [comment]
@maxfenton that's correct, it should be resolved now

**Comment by erusev** [comment]
@hkdobrev could u have a quick look at the failing build at https://travis-ci.org/erusev/parsedown-extra/jobs/85614579

it looks related to late static binding

**Comment by hkdobrev** [comment]
@erusev It's failing, because `ParsedownExtraTest` extends `ParsedownTest` and this way PHPUnit executes both testsuites. I don't think that's needed. However if you really want to keep it this way, we'll need to change the way the `TestParsedown.php` file is loaded.

**Comment by erusev** [comment]
it extends `ParsedownTest` because we want to make sure that "extra" doesn't break the parsing of the original syntax.
