### ISSUE TITLE
Special Attributes on Fenced Code Blocks

### ISSUE THREAD

**Issue by Stolzenhain** [erusev/parsedown-extra#74]
Parsedown Extra supports [fenced code blocks](https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks) and [special attributes](https://michelf.ca/projects/php-markdown/extra/#spe-attr) on titles, but sadly not the combination of both (which is helpful for code highlighters, for example). 

I'm not sure if you're planning to support the whole Markdown Extra spec, but are you still considering to support a wider range of attributes?

**Comment by Stolzenhain** [comment]
Ok – I guess I found something about this in an [extension](https://github.com/egil/php-markdown-extra-extended) – working this out.

**Comment by Stolzenhain** [comment]
Ok – I didn't find any docs on this, but writing 

    ~~~~~~~~~ html
    <a href="#anchor">Link Text</a>
    ~~~~~~~~~

outputs 

    <pre>
        <code class="language-html">
            &lt;a href="#anchor"&gt;Link Text&lt;/a&gt;
        </code>
    </pre>

that is, prepending the string with ``language-``and adding it as a class. 
That's not Markdown Extra spec but a safe implementation of the technique – closing thread.

**Comment by hkdobrev** [comment]
Just to clarify, this behaviour is from Parsedown itself adhering to the way GitHub implements GFM.

**Comment by Stolzenhain** [comment]
Ah right! I thought something like that while writing the issue comment. I guess that's simply how these edge cases evolve.
