### ISSUE TITLE
Error: Undefined class constant 'version' 

### ISSUE THREAD

**Issue by mastito03** [erusev/parsedown-extra#84]
it's show
`PHP Fatal error:  Undefined class constant 'version' in /home/mastito/www/submeets/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 26`

probably because `version` in parsedown extra using lower case.

**Comment by cebe** [comment]
both classes have a `version` constant:

https://github.com/erusev/parsedown-extra/blob/master/ParsedownExtra.php#L20
https://github.com/erusev/parsedown/blob/master/Parsedown.php#L20

**Comment by cebe** [comment]
seems you are using an old version of Parsedown, that does not have a the version constant.

**Comment by mastito03** [comment]
I'm using version 1.6.0

but in line 20, `version` is written in uppercase

I don't know why it's different from github version, which uses lowercase

**Comment by cebe** [comment]
the 1.6.0 tag has it in lower case: https://github.com/erusev/parsedown/blob/1.6.0/Parsedown.php#L20
