### ISSUE TITLE
multiple classes possible?

### ISSUE THREAD

**Issue by jerry1970** [erusev/parsedown-extra#88]
This of course gets a code fenced block:
~~~
    ``` classname1
    some code;
    ```
~~~

This parses into a DIV (and not CODE) with a class:
~~~
    ``` classname1
    Some text.
    ```
~~~

But how can I get two classes on the DIV? This does not work:
~~~
    ``` classname1 classname2
    Some text.
    ```
~~~

Thanks!

**Comment by erusev** [comment]
No, this is not possible.
